# Generated by Django 2.0.3 on 2018-04-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employees',
            table='employees',
        ),
    ]
